### ISSUE TITLE
`zsh: command not found: ember` on installation instructions

### ISSUE THREAD

**Issue by defeed** [bazzel/ember2-workshop#5]
What I did:

```
git clone this repository
cd ember-workshop/frontend
npm install
bower install
ember s --proxy https://ember2-workshop-backend.herokuapp.com
```

What I got:

```
➜  frontend git:(master) ember s --proxy https://ember2-workshop-backend.herokuapp.com
zsh: command not found: ember
```

What I expect: ember to run a server

**Comment by bazzel** [comment]
I except you have to install ember-cli globally, using `npm install -g ember-cli` before you can use the `ember` command.
I myself used the instructions shown on the [Ember CLI site](http://www.ember-cli.com/user-guide/#getting-started).
Hope this will help.

**Comment by defeed** [comment]
@bazzel yes, that was the case :+1: thanks for the quick response!

**Comment by bazzel** [comment]
Thank you for testing :)
