### ISSUE TITLE
04.0.0 Upload file has a typo

### ISSUE THREAD

**Issue by eirvandelden** [bazzel/ember2-workshop#6]
After adding the [gist](https://gist.github.com/bazzel/560eb7510ada3d41e680#file-upload-file-js) for the upload-file.js, uploading still doesn't work with the following error:

```
upload-file.js:14 Uncaught ReferenceError: _this is not defined(anonymous function) @ upload-file.js:14Backburner.run @ ember.debug.js:294run @ ember.debug.js:19661reader.onload @ upload-file.js:13
```

**Comment by eirvandelden** [comment]
The gist should refer to `this`, not `_this`.
See here: https://gist.github.com/eirvandelden/92423caf8f90a5fc0a21

**Comment by bazzel** [comment]
Yep, result of copy/paste from a previous workshop. gist updated.
