### ISSUE TITLE
05.0.0 Error in code wiki code

### ISSUE THREAD

**Issue by eirvandelden** [bazzel/ember2-workshop#8]
Filter the products:
`search = new RegExp(this.get('application.search'), 'i');`
should be
`var search = new RegExp(this.get('application.search'), 'i');`

The variable search hasn't been defined yet.

**Comment by bazzel** [comment]
Almost... if you close, the code samples uses `,` (comma), not `;` on the previous line.

Still thanks for notifying.

```
var products = this.model,
      search = new RegExp(this.get('application.search'), 'i');
```
